stages:
  - install_deps
  - build
cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
     
# 安装依赖
install_deps:
  stage: install_deps
  only:
    - develop
    - master
  script:
    - npm install --registry=https://registry.npm.taobao.org
# 编译
build:
  stage: build
  only:
    - develop
    - master
  script:
    - webpack